### ISSUE TITLE
Cannot update for Swift 3

### ISSUE THREAD

**Issue by maysamsh** [ephread/Instructions#69] opened 2016-09-11 10:24 UTC
I get this error message (XCode 8 GM):
`The following build commands failed:
	PhaseScriptExecution Run\ Script build/Instructions.build/Release-iphoneos/Instructions.build/Script-C6B30BA61D529E1000505F0C.sh`

**Comment by ephread** [comment] 2016-09-13 20:47
Hello @maysamsh, thanks for reporting the issue.

1. Which method did you use to install Instructions (CocoaPods, Carthage or Manual)?
2. Are you using the `swift3` branch?

**Comment by maysamsh** [comment] 2016-09-14 03:57
Hey,
I'm using Carthage and swift3 branch

**Comment by ephread** [comment] 2016-09-14 10:27
I can't reproduce the issue, have you tried cleaning the build directory, as well as nuking the derived data? Alternatively, could you provide me with a sample project which illustrates the problem?

**Comment by maysamsh** [comment] 2016-09-14 10:58
I'm not sure how can I use swift3 branch, is it the same as original repo but version 0.5 and higher?

**Comment by ephread** [comment] 2016-09-14 11:30
You only need to use this line in your Cartfile:

```
github "ephread/Instructions" "swift3"
```

This branch will be updated alongside `master`, tracking bugfixes and new features. When Swift 3 will come out, the branch will be merged back into `master` and the Swift 2 version will be deprecated.

Additionally, the README found in `swift3` hasn't been updated yet and doesn't reflect the state of library. I plan on writing a quick migration guide, since few methods have been renamed to match the new guidelines found in Swift 3.

**Comment by maysamsh** [comment] 2016-09-18 03:48
I tried `swift3` branch and failed again:
`A shell task (/usr/bin/xcrun xcodebuild -workspace /pathtoproject/Carthage/Checkouts/Instructions/Instructions.xcworkspace -scheme Instructions -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **`

**Comment by maysamsh** [comment] 2016-09-18 04:48
Ironically the problem was it needed a `.profile` folder in `home` folder.

**Closed** 2016-09-18 04:52 UTC

**Comment by ephread** [comment] 2016-11-06 00:38
Fixed by #76.
