### ISSUE TITLE
Xcode 11 Build Issue: "~/Library/Developer/Xcode/DerivedData/LIKE-hgpysltcapxaaqbkjnoggrxhteud/Build/Products/Debug-iphoneos/xxx.app/Assets.car' "

### ISSUE THREAD

**Issue by coreypett** [ephread/Instructions#227] opened 2019-11-30 18:01 UTC
After I updated to xcode11, the new build system didn't work. An error occurred with below message
"Multiple commands produce '~/Library/Developer/Xcode/DerivedData/LIKE-hgpysltcapxaaqbkjnoggrxhteud/Build/Products/Debug-iphoneos/xxx.app/Assets.car' "

I think the reason is "s.resources = [ "Instructions/**/Assets.xcassets"] " in podspec file, which will lead pod create a copy script like this "${PODS_ROOT}/TrueSDK/TrueSDK/External/Assets.xcassets". And the name of "Assets" is multiple with the main target's image xcassets.

I think you should remove the "s.resources = [ "Instructions/**/Assets.xcassets"] ", and put the Assets.xcassets into the "resource_bundles" tag, which will create a bundle to fold the assets.xcassets.

**Comment by ephread** [comment] 2019-12-01 06:24
Thanks for reporting the issue @coreypett and suggesting an alternative approach. I’ll have a look when I’m back. I’ve never used resource bundles before, hence my question: won’t this break the current approach when using Carthage or manually embedding the framework? (I’m assuming, perhaps incorrectly, that the assets will now sit in different bundles depending on which package manager is used.) Maybe I could simply rename `Assets.xcassets` to `Instructions.xcassets`?

**Comment by vicajilau** [comment] 2020-02-06 11:01
> Después de actualizar a xcode11, el nuevo sistema de compilación no funcionó. Se produjo un error con el siguiente mensaje
> "Múltiples comandos producen '~ / Library / Developer / Xcode / DerivedData / LIKE-hgpysltcapxaaqbkjnoggrxhteud / Build / Products / Debug-iphoneos / xxx.app / Assets.car'"
> 
> Creo que la razón es "s.resources = [" Instrucciones / ** / Assets.xcassets "]" en el archivo podspec, lo que llevará al pod a crear una secuencia de comandos de copia como esta "$ {PODS_ROOT} / TrueSDK / TrueSDK / External / Assets .xcassets ". Y el nombre de "Activos" es múltiple con los xcassets de imagen del objetivo principal.
> 
> Creo que debería eliminar "s.resources = [" Instrucciones / ** / Assets.xcassets "]" y colocar Assets.xcassets en la etiqueta "resource_bundles", lo que creará un paquete para plegar los assets.xcassets.

I have the same problem, is there any solution? 

![image](https://user-images.githubusercontent.com/34163765/73931328-6867f280-48d8-11ea-8bd4-e9bb736471af.png)

**Comment by vicajilau** [comment] 2020-02-06 11:03
> After I updated to xcode11, the new build system didn't work. An error occurred with below message
> "Multiple commands produce '~/Library/Developer/Xcode/DerivedData/LIKE-hgpysltcapxaaqbkjnoggrxhteud/Build/Products/Debug-iphoneos/xxx.app/Assets.car' "
> 
> I think the reason is "s.resources = [ "Instructions/**/Assets.xcassets"] " in podspec file, which will lead pod create a copy script like this "${PODS_ROOT}/TrueSDK/TrueSDK/External/Assets.xcassets". And the name of "Assets" is multiple with the main target's image xcassets.
> 
> I think you should remove the "s.resources = [ "Instructions/**/Assets.xcassets"] ", and put the Assets.xcassets into the "resource_bundles" tag, which will create a bundle to fold the assets.xcassets.

I have the same problem. Is there any solution?

![image](https://user-images.githubusercontent.com/34163765/73931442-9baa8180-48d8-11ea-8800-67b2a3aa3ea9.png)

**Comment by ephread** [comment] 2020-03-17 11:26
I've checked with the latest version (1.4.0) and I can't reproduce any of these issues. Have you tried with the latest version?

**Comment by ephread** [comment] 2020-04-01 20:36
Since there's no longer an asset bundle in `master`, I'm closing this issue. Feel free to reopen if you still encounter issues with the coming version.

**Closed by ephread** 2020-04-01 20:36 UTC
