### ISSUE TITLE
App freezes while running

### ISSUE THREAD

**Issue by psubhashish** [ephread/Instructions#108] opened 2017-05-03 09:54 UTC
![img_1891](https://cloud.githubusercontent.com/assets/1258090/25655932/76b0da62-3014-11e7-9781-c423fbe7d2de.PNG)
The app just froze like the above and I could not do anything but shut it down forcefully.

**Comment by ephread** [comment] 2017-05-18 15:07
Hello @psubhashish, is it caused by Instructions? I can't seem to identified anything related to Instructions on your screenshot, could you provide me with a bit more details?

**Comment by psubhashish** [comment] 2017-05-19 07:50
I'm not sure actually. I was trying to record and it just froze. I tried to restart the app and there was no progress.

**Comment by ephread** [comment] 2017-06-03 21:34
I'm closing, as it doesn't seem to be caused by Instructions. If you've got more details on the issue, feel free to re-open.

**Closed by ephread** 2017-06-03 21:34 UTC
