### ISSUE TITLE
Navigation Bar Button Item not tappable on iOS 11

### ISSUE THREAD

**Issue by kaustubhtj** [ephread/Instructions#144] opened 2017-11-08 11:52 UTC
I have created UIBarButton item with UIButton as a custom view. Till iOS 10 it was tappable through the overlay but now with iOS 11 it is not working. 

any suggestion ?

Here is my code
`let setting =   UIButton.init(type: .custom)`
`let frame:CGRect = CGRect(x: 0, y: 0, width: 44, height: 44)`
`setting.setImage( UIImage(named: "settings"), for: .normal)`
`setting.addTarget(self, action: #selector(AlertHistoryViewController.loadSettingScreen), for: .touchUpInside)`
`setting.frame = frame`
`navigationItem.rightBarButtonItem = UIBarButtonItem.init(customView: setting)`

**Comment by ephread** [comment] 2017-11-16 10:21
Hey @kaustubhtj, are you using `CoachMark.allowTouchInsideCutoutPath`, to allow touch forwarding?

**Comment by kaustubhtj** [comment] 2017-11-16 10:56
@ephread Yup

public func coachMarksController(_ coachMarksController: CoachMarksController, coachMarkAt index: Int) -> CoachMark {
        var coachMark : CoachMark
        switch(index) {
        case 0:
            let rightBarButton = self.navigationItem.rightBarButtonItem
            
            coachMark = coachMarksController.helper.makeCoachMark(for: rightBarButton?.customView!) { (frame: CGRect) -> UIBezierPath in
                ripple(CGPoint(x: frame.origin.x + frame.width/2, y: frame.height/2), view: (self.navigationController?.navigationBar)!)
                return UIBezierPath(ovalIn: frame.insetBy(dx: -4, dy: -4))
            }
        default:
            coachMark = coachMarksController.helper.makeCoachMark()
        }
        coachMark.allowTouchInsideCutoutPath = true
        coachMark.gapBetweenCoachMarkAndCutoutPath = 10
        return coachMark
    }

**Comment by ephread** [comment] 2017-11-16 11:29
Looks like a bug, I'll take a look.

**Comment by kaustubhtj** [comment] 2017-12-05 07:40
@ephread Thanks. Will wait to hear from you.

**Comment by k0mach1** [comment] 2019-04-23 02:10
@ephread 
I also face the same problem...
Do you have a plan to fix this in recent?

**Comment by ephread** [comment] 2020-04-01 20:41
I've never been able to reproduce the problem and since I'm going to drop support for iOS 11 soon, I'm going to close the issue. If anyone encounters this problem again and can provide me with a sample project, feel free to open a new issue!

**Closed by ephread** 2020-04-01 20:41 UTC
Labels: bug
