### ISSUE TITLE
start(on:) is deprecated, unable to use start(in:)

### ISSUE THREAD

**Issue by sandman4sure** [ephread/Instructions#198] opened 2019-02-13 09:32 UTC
I get a deprecation warning when I use `coachMarksController.start(on:)` saying to use `start(in:)`

Problem is I can not use that function, it is not added to the autocomplete, probably because I can not use PresentationContext:
`Use of unresolved identifier 'PresentationContext'`

I have added Instructions to my project using cocoa pods as described in your readme.

**Comment by ephread** [comment] 2019-02-13 09:44
Hi @sandman4sure, are you using the latest version (1.2.2)? Did you use Carthage / CocoaPods or added the framework manually?

**Comment by sandman4sure** [comment] 2019-02-13 09:49
Yes, I am using 1.2.2 and use CocoaPods for adding it:

```
platform :ios, '10.0'
target 'X' do
	use_frameworks!
  	pod 'Instructions', '~> 1.2.2'
end
```

**Comment by ephread** [comment] 2019-02-13 10:10
I can reproduce the issue. That's a strange one, the files are present in the `Pods/` directory, but somehow not included in the build. Sorry about that, I'm going on a trip tomorrow morning and probably won't be able to investigate before at least two weeks.

**Comment by sandman4sure** [comment] 2019-02-13 10:11
No problem, glad you can reproduce it.

**Comment by subhadeep-pal** [comment] 2019-02-25 11:18
Is this resolved yet?

**Comment by ephread** [comment] 2019-03-03 05:37
As expected, the reasons for this issue are somewhat unclear. It seems that the compiler gets confused by `PresentationContext.newWindow` having a `UIWindow.Level?` associated object. If you remove it or replace it by another type, compilation goes through successfully.

It's a very peculiar _bug_, that seems to happen only with CocoaPods. I don't believe it's an issue with the packagae manager though, rather, I think there's something strange going on in the toolchain. The fact that it doesn't happen with Carthage lead me to think that a slight tweak in the build config could be a valid workaround.

I need to investigate more and if I'm able to create a simple project showcasing the issue, I'll fill a radar. In the meantime, I'm going to spawn a workaround branch for people using CocoaPods, where the `UIWindow.Level` will be replaced with its `float` raw value.

**Comment by ephread** [comment] 2019-03-03 06:49
@sandman4sure & @subhadeep-pal, can you confirm that `1.2.2-workaround` works for you?

```ruby
pod 'Instructions', :git => 'https://github.com/ephread/Instructions.git', :tag => '1.2.2-workaround'
```

Also, see [here](https://github.com/ephread/Instructions/tree/1.2.2-workaround#%EF%B8%8F-cocoapods-users).

**Comment by sandman4sure** [comment] 2019-03-04 13:57
Yes, that one seems to work.
Will this stay on the workaround branch?

**Comment by BeechMachine** [comment] 2019-03-04 21:01
Watching this hopefully...

**Comment by ephread** [comment] 2019-03-05 12:52
@sandman4sure for now, until I can investigate more. I'll make a special pod release and update the README on `master` when I get the chance though.

**Comment by rgkobashi** [comment] 2019-03-12 03:32
Hi,
I am having this same problem but downloading this pod from `1.2.2-workaround` is not working for me. I am getting `Failed to download Instructions` when running `pod install`. Did someone have this problem? This is the full output I am getting when running on verbose mode.
```
-> Pre-downloading: `Instructions` from `https://github.com/ephread/Instructions.git`, tag `1.2.2-workaround`
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/ephread/Instructions.git
     /var/folders/wv/298ml25j19n3g583sxfd6h7h0000gn/T/d20190312-27486-1f8exe8 --template= --single-branch
     --depth 1 --branch 1.2.2-workaround
     Cloning into '/var/folders/wv/298ml25j19n3g583sxfd6h7h0000gn/T/d20190312-27486-1f8exe8'...
     Note: checking out 'fc7d76e7e8a6a21801e2b7c83b07ec8f4e9b8754'.
     
     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.
     
     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:
     
       git checkout -b <new-branch-name>
     
[!] Failed to download 'Instructions'.
```
Thanks in advance.

**Comment by ephread** [comment] 2019-03-12 08:24
@rgkobashi: awkward, git throws no error. Do you have Git LFS installed?

**Comment by rgkobashi** [comment] 2019-03-15 09:00
oooh, maybe is because of that 😅 I dont have it installed.
Thanks for your reply!

**Comment by YassineDaoudi** [comment] 2019-03-27 10:54
still got the same error as @rgkobashi even after installing Git LFS

`Analyzing dependencies
Pre-downloading: `Instructions` from `https://github.com/ephread/Instructions.git`, tag `1.2.2-workaround`
[!] Failed to download 'Instructions'.`

**Comment by ephread** [comment] 2019-03-27 20:55
@YassineDaoudi, @rgkobashi, I can't reproduce the issue you're both having.

BUT, it appears that Swift 5 fixes the issue, so the workaround is no longer needed. Swift 5 being largely compatible with Swift 4, CocoaPods should not complain if you're importing Swift 4 code into a Swift 5 project (and vice-versa).

**Comment by YassineDaoudi** [comment] 2019-04-05 14:30
@ephread Sorry to disappoint you but even in swift 5 it isn't working :/

**Comment by YassineDaoudi** [comment] 2019-04-05 14:33
`Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Instructions":
  In Podfile:
    Instructions (~> 1.2.2)

None of your spec sources contain a spec satisfying the dependency: `Instructions (~> 1.2.2)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.`

**Comment by ephread** [comment] 2019-05-04 10:09
Seems fixed, so I'm closing the issue.

**Closed by ephread** 2019-05-04 10:09 UTC
Labels: bug

**Comment by anushkmittal** [comment] 2019-05-12 05:08
@ephread is there a workaround for Swift 4.2 not throwing this warning?

**Comment by ephread** [comment] 2019-05-12 06:37
@anushkmittal I'm not sure I understand what your question is, can you elaborate?

**Comment by anushkmittal** [comment] 2019-05-13 10:59
my project is on swift version 4.2 so i see that warning. 

i understand swift 5 has it fixed but if there was a workaround to get rid of it on a 4.2 project

**Comment by ephread** [comment] 2019-05-13 19:54
If you're talking about the deprecation warning, you just have to use `start(in:)` instead of `start(on:)`, but this warning has nothing to do with the Swift version, you'd have it with either version of Swift.

If you're talking about the toolchain bug with CocoaPods, you can use the `1.2.2-workaround` branch. 

I'm a bit confused as to what your question is exactly.

**Comment by rhkrthdud7** [comment] 2019-05-20 09:22
So if I understood correctly for people who are having a warning while using this library the right way, for swift 5 projects it is fixed so you won't see one and on the other side for below swift 5 projects you can use the workaround branch. Am I right?
