### ISSUE TITLE
Xcode is saying CoachMarksController' has no member 'start'

### ISSUE THREAD

**Issue by ahsanaasim** [ephread/Instructions#224] opened 2019-10-24 06:22 UTC
**Describe the bug**
When I use this line, 
`self.coachMarksController.start(in: .window(over: self))`
New Version of 11.1 is showing the following error:
`Value of type 'CoachMarksController' has no member 'start'`

**To Reproduce**
In the previous version of Xcode, it was working. But not working in Xcode 11.1

**Expected behavior**
I have seen inside CoachMarksController class. start method actually exists. But still, Xcode is showing this error message.

**Screenshots**
![Screenshot 2019-10-24 at 12 17 00 PM](https://user-images.githubusercontent.com/17532073/67458524-38ae1b00-f658-11e9-82a8-7fac9902bf2e.png)

**Environment:**
- Xcode: 11.1
- Swift 5
 - Device:  Any
 - iOS version: 11.3
 - Dependency Manager: CocoaPods

**Comment by derekgraham** [comment] 2019-10-24 19:37
Same. Updated from 'master' to 1.4 in my cart file. Previously I was getting an odd message about Start(on:) being deprecated in 1.2.1 but I was not able to change it to the recommended start(in:). Not not recognizing start as a method of CoachMarksController.

**Comment by derekgraham** [comment] 2019-10-24 22:16
I 'fixed' this for me by updating my app to Swift 5, which finally got it to recognize a method with ProcessContext as a parameter. Hacking around on my local copy my notes:
 - I was able to add a method that showed up when I rebuilt my app with the newly built framework (func mylittlepony(in: Bool). 
- when I changed the Bool to ProcessContext (enum) mylittlepony no longer showed up as method in autocomplete.
- I had also tried moving around the #if #else but that didn't make a difference
- I've had to update my call to .start with the enum format and that part seems to be working (i.e. it starts when loading that view controller as it used to).
- Previously I had been using Xcode 11.1 but hadn't updated to Swift 5 for my code yet.

**Comment by derekgraham** [comment] 2019-10-24 22:17
Oh and once I updated to Swift 5, it offered to change my .start(on:) to .start(in:)

**Comment by ephread** [comment] 2019-11-22 21:03
Ah, thanks for the context @derekgraham. There was a bug in the Swift 4.x toolchain that happened only with CocoaPods, which is likely related to this issue, see #198.

I'll have to investigate and see if it still happens with Swift 5, but as far as I know it doesn't.

**Comment by ephread** [comment] 2022-05-25 20:59
Closing this, as I'm certain it was caused by a bug in the toolchain 3 years ago. It's been working well since (as far as I know).

**Closed by ephread** 2022-05-25 20:59 UTC
Labels: bug, top priority
